<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="6" failures="0" disabled="0" errors="0" time="0" timestamp="2021-10-04T18:37:11.090" name="AllTests">
  <testsuite name="std_exception_test_suite" tests="6" failures="0" disabled="0" skipped="0" errors="0" time="0" timestamp="2021-10-04T18:37:11.090">
    <testcase name="test_catch_go_exception" status="run" result="completed" time="0" timestamp="2021-10-04T18:37:11.090" classname="std_exception_test_suite" />
    <testcase name="test_catch_go_exception_as_std_exception" status="run" result="completed" time="0" timestamp="2021-10-04T18:37:11.091" classname="std_exception_test_suite" />
    <testcase name="test_catch_derived_exception" status="run" result="completed" time="0" timestamp="2021-10-04T18:37:11.091" classname="std_exception_test_suite" />
    <testcase name="test_catch_derived_exception_as_go_exception" status="run" result="completed" time="0" timestamp="2021-10-04T18:37:11.091" classname="std_exception_test_suite" />
    <testcase name="test_catch_derived_exception_as_std_exception" status="run" result="completed" time="0" timestamp="2021-10-04T18:37:11.091" classname="std_exception_test_suite" />
    <testcase name="test_catch_other_exception" status="run" result="completed" time="0" timestamp="2021-10-04T18:37:11.091" classname="std_exception_test_suite" />
  </testsuite>
</testsuites>
