<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="6" failures="0" disabled="0" errors="0" timestamp="2019-04-17T18:08:16" time="0.007" name="AllTests">
  <testsuite name="std_exception_test_suite" tests="6" failures="0" disabled="0" errors="0" time="0.004">
    <testcase name="test_catch_go_exception" status="run" time="0" classname="std_exception_test_suite" />
    <testcase name="test_catch_go_exception_as_std_exception" status="run" time="0" classname="std_exception_test_suite" />
    <testcase name="test_catch_derived_exception" status="run" time="0" classname="std_exception_test_suite" />
    <testcase name="test_catch_derived_exception_as_go_exception" status="run" time="0" classname="std_exception_test_suite" />
    <testcase name="test_catch_derived_exception_as_std_exception" status="run" time="0" classname="std_exception_test_suite" />
    <testcase name="test_catch_other_exception" status="run" time="0" classname="std_exception_test_suite" />
  </testsuite>
</testsuites>
