<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="6" failures="0" disabled="0" errors="0" time="0.009" timestamp="2021-12-30T22:00:59.395" name="AllTests">
  <testsuite name="std_exception_test_suite" tests="6" failures="0" disabled="0" skipped="0" errors="0" time="0.007" timestamp="2021-12-30T22:00:59.396">
    <testcase name="test_catch_go_exception" status="run" result="completed" time="0" timestamp="2021-12-30T22:00:59.396" classname="std_exception_test_suite" />
    <testcase name="test_catch_go_exception_as_std_exception" status="run" result="completed" time="0" timestamp="2021-12-30T22:00:59.397" classname="std_exception_test_suite" />
    <testcase name="test_catch_derived_exception" status="run" result="completed" time="0" timestamp="2021-12-30T22:00:59.397" classname="std_exception_test_suite" />
    <testcase name="test_catch_derived_exception_as_go_exception" status="run" result="completed" time="0" timestamp="2021-12-30T22:00:59.402" classname="std_exception_test_suite" />
    <testcase name="test_catch_derived_exception_as_std_exception" status="run" result="completed" time="0" timestamp="2021-12-30T22:00:59.403" classname="std_exception_test_suite" />
    <testcase name="test_catch_other_exception" status="run" result="completed" time="0" timestamp="2021-12-30T22:00:59.403" classname="std_exception_test_suite" />
  </testsuite>
</testsuites>
